name: Run tests

on:
  push:
    branches: "*"

jobs:
  Compile:
    name: Compile
    runs-on: ubuntu-latest
    container:
      image: postgres:latest
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test
      ports:
        - 5432:5432
    steps:
      - name: Setup Java 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build
        uses: actions/checkout@v4
        run: ./gradlew tests



