name: Run tests

on:
  push:
    branches: "*"

jobs:
  Compile:
    name: Compile
    runs-on: ubuntu-latest
    container:
      image: postgres:latest
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: test
      ports:
        - 5432:5432
    steps:
      - run: echo "Hello"



